sudo: false

language: haxe

haxe:
  - "3.2.1"
  - development

neko: "2.1.0"

os:
  - linux
  - osx
 
addons:
  apt:
    packages:
      - libcurl4-openssl-dev

matrix:
  allow_failures:
    - haxe: development

before_script:
  - ldconfig

script:
  - pushd lib
  - make all
  - popd

after_success:
  - pushd lib
  - make install
  - make test
  - popd
